# Generated by Django 3.1.6 on 2021-02-11 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Crop')),
                ('crop_drz', models.PositiveIntegerField(null=True, verbose_name='Depth of Root Zone (mm)')),
                ('crop_dtm', models.PositiveIntegerField(null=True, verbose_name='Days to Maturity')),
                ('stage_init', models.PositiveIntegerField(null=True, verbose_name='Stage init (days)')),
                ('stage_dev', models.PositiveIntegerField(null=True, verbose_name='Stage dev (days)')),
                ('stage_mid', models.PositiveIntegerField(null=True, verbose_name='Stage mid (days)')),
                ('stage_late', models.PositiveIntegerField(null=True, verbose_name='Stage late (days)')),
                ('kc_init', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Kc init')),
                ('kc_mid', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Kc dev')),
                ('kc_late', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Kc late')),
                ('personal', models.BooleanField(default=True)),
                ('reference', models.CharField(max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_type', models.CharField(max_length=20, null=True, verbose_name='Station Type')),
                ('station_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Station Name')),
                ('station_elev', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Station Elevation (m)')),
                ('station_lat', models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Latitude (°)')),
                ('station_long', models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Longitude (°)')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Soil')),
                ('soil_fc', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Field Capacity (mm H2O/mm soil)')),
                ('soil_pwp', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Permanent Wilting Point (mm H2O/mm soil)')),
                ('percolation', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Percolation (mm)')),
                ('init_depl', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Initial Depletion (mm)')),
                ('mad', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Management Allowable Depletion (mm H2O/mm soil)')),
                ('personal', models.BooleanField(default=True)),
                ('reference', models.CharField(max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prov', models.CharField(default=None, max_length=20, verbose_name='Province')),
                ('muni', models.CharField(default=None, max_length=20, verbose_name='Municipality')),
                ('brgy', models.CharField(default=None, max_length=20, verbose_name='Barangay')),
                ('date_planted', models.DateField(blank=True, default=None, null=True, verbose_name='Planting Date')),
                ('corr_factor', models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='Correction Factor')),
                ('crop', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.crop')),
                ('manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soil', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.soil')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(blank=True, null=True, verbose_name='Date Measured')),
                ('eto', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Reference Evapotranspiration (mm)')),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Rainfall (mm)')),
                ('irrigation', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Irrigation (mm)')),
                ('farm', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.farm')),
                ('station', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.station')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
