# Generated by Django 3.1.6 on 2021-02-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etcal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(default=None, max_length=20, verbose_name='Crop'),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateField(null=True, verbose_name='Date Measured'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.crop'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='date_planted',
            field=models.DateField(default=None, verbose_name='Planting Date'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.soil'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soil_type',
            field=models.CharField(default=None, max_length=20, verbose_name='Soil'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Station Name'),
        ),
    ]
