# Generated by Django 3.1.6 on 2021-02-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etcal', '0002_auto_20210211_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='brgy',
            new_name='farm_brgy',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='muni',
            new_name='farm_muni',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='prov',
            new_name='farm_prov',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='name',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude (°)'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude (°)'),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Farm Name'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_brgy',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Barangay'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_muni',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_prov',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_mid',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Kc mid'),
        ),
        migrations.AlterField(
            model_name='data',
            name='farm',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.farm'),
        ),
        migrations.AlterField(
            model_name='data',
            name='station',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etcal.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_elev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Station Elevation (m)'),
        ),
    ]
