# Generated by Django 3.1.6 on 2021-02-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etcal', '0003_auto_20210211_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='eto',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Reference Evapotranspiration (mm)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='irrigation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Irrigation (mm)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rainfall',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Rainfall (mm)'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_brgy',
            field=models.CharField(default=None, max_length=30, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_muni',
            field=models.CharField(default=None, max_length=30, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Farm Name'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_prov',
            field=models.CharField(default=None, max_length=30, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_brgy',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_muni',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Station Name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_prov',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Province'),
        ),
    ]
