# Generated by Django 3.1.6 on 2021-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etcal', '0004_auto_20210212_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='date_planted',
            field=models.DateField(default=None, null=True, verbose_name='Planting Date'),
        ),
    ]
